services:
  abp_host:
    build:
      context: ../
      dockerfile: ./src/SafeGuard.Web.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "${DB_CONNECTION_STRING}"
      App__ServerRootAddress: "http://localhost:44311/"
      App__ClientRootAddress: "http://localhost:4200/"
      App__CorsOrigins: "http://localhost:4200,http://localhost:3000"
      AzureComputerVision__ApiKey: "${AzureComputerVision__ApiKey}"
      AzureComputerVision__Endpoint: "${AzureComputerVision__Endpoint}"
      Blockchain__HmacSecret: ${BLOCKCHAIN_HMAC_SECRET}
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always
