import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
  },
  leftPanel: {
    flex: '0 0 45%',
    background: 'linear-gradient(160deg, #0a0f1e 0%, #0d2149 45%, #0a0f1e 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '64px 48px',
    color: '#fff',
    position: 'relative',
    overflow: 'hidden',
  },
  leftPanelInner: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
  },
  brandIcon: {
    fontSize: 56,
    color: '#60a5fa',
    marginBottom: 20,
  },
  brandTitle: {
    fontSize: 36,
    fontWeight: 800,
    color: '#fff',
    margin: 0,
    letterSpacing: '-0.5px',
  },
  brandTagline: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 12,
    lineHeight: 1.7,
    maxWidth: 280,
  },
  divider: {
    width: 40,
    height: 3,
    background: 'linear-gradient(90deg, #3b82f6, #60a5fa)',
    borderRadius: 2,
    margin: '28px 0',
  },
  featureList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    alignSelf: 'stretch',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    color: '#cbd5e1',
    fontSize: 14,
  },
  featureIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: 'rgba(59, 130, 246, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: '#60a5fa',
    fontSize: 15,
  },
  rightPanel: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 32px',
    background: '#f8fafc',
  },
  formWrapper: {
    width: '100%',
    maxWidth: 420,
  },
  formHeader: {
    marginBottom: 32,
  },
  formTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
  },
  formSubtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 6,
  },
  submitButton: {
    width: '100%',
    height: 44,
    fontSize: 15,
    fontWeight: 600,
  },
  signupRow: {
    textAlign: 'center',
    marginTop: 24,
    fontSize: 14,
    color: '#64748b',
  },
  mobileBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 32,
  },
};
